config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'restaurants', to: 'restaurants#index', as: 'restaurants'
  get 'restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  post 'restaurants', to: 'restaurants#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true,
    inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true },
    inclusion: { in: (0..5).to_a, allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Yelp", restaurants_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Restaurant list", restaurants_path %></li>
      <li><%= link_to "Add restaurant", new_restaurant_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="wrapper">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, placeholder: "Errioguarda" %>
  <%= f.input :address, placeholder: "Hernani Gipuzkoa" %>
  <%= f.input :phone_number, placeholder: "949 768 989" %>
  <%= f.input :category, placeholder: "Italian" %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurant list</h1>
<ul>
<% @restaurants.each do |restaurant| %>
  <li>
    <h3><%= restaurant.name %></h3>
    <p><%= restaurant.category.capitalize %></p>
    <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
  </li>

<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.category.capitalize %> restaurant</p>
<p><%= @restaurant.address.capitalize %></p>
<p>Phone: <%= @restaurant.phone_number %></p>
<h3>Reviews</h3>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <p><%= review.content.capitalize %></p>
      <p><strong>Rating: <%= review.rating %></strong></p>
    </li>
  <% end %>
</ul>


<%= render 'review_form' %>